### ISSUE TITLE
getting ! zlib: unexpected end of file

### ISSUE THREAD

**Issue by ronnizan** [chromaui/intro-storybook-react-template#9]
when running the commend : npx degit chromaui/intro-storybook-react-template taskbox im getting : ! zlib: unexpected end of file
any idea why?

**Comment by jonniebigodes** [comment]
@ronnizan thanks for reaching out to us with your issue. Looking at the information it seems that this is not actually related to the template itself but rather with [degit](https://github.com/Rich-Harris/degit). Could you check this [link](https://github.com/Rich-Harris/degit/issues?q=is%3Aissue+is%3Aopen+zlib%3A+unexpected+end+of+file) and see if the solutions mentioned help you in any way and follow up with me?

Have a great week!


Stay safe
